# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='user_search',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
