# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20160804_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='user_search',
            new_name='search_text',
        ),
    ]
