# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_search', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
